<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DrugSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (range(1, 10) as $i) {
            $names = [
                "Aceite de Higado de Bacalao Emulsión",
                "Acetaminofén (Paracetamol)",
                "Acetaminofen (Paracetamol) 100 mg Supositorio",
                "Acetaminofen (Paracetamol) Gotas Pedatricas 100 mg/ml",
                "Acetaminofen (Paracetamol) Jbe. 125mg/5ml",
                "Acetaminofen+Cafeina",
                "Acetato De Medroxiprogesterona Inyección de Liberación Retardada 150 mg/ml",
                "Acetilcisteína",
                "Aciclovir",
                "Aciclovir 200 mg/5 mL Suspensión",
                "Aciclovir Crema",
                "Acido Acetilsalicílico 325mg",
                "Acido Acetilsalicílico 81mg",
                "Acido Ascórbico (Vit. C) 500 mg",
                "Acido Fólico 5 mg",
                "Acido Fólico + Vit. B12 (5mg + 500mcg)/ 5mL",
                "Acido Fólico 5mg/5mL Jarabe",
                "Acido Mefenámico",
                "Ácido Valpróico",
                "Acido valproico 200 mg/ml Solucion Oral",
                "Agua Para Inyectable",
                "Agua Para Inyetable",
                "Albendazol Suspensión (dosis única)",
                "Albendazol 400 mg (dosis unica)",
                "Albúmina Humana 20%",
                "Alcohol Isopropílico",
                "Alendronato",
                "Algodón Torunda",
                "Alopurinol 300 mg",
                "Ambroxol",
                "Ambroxol 15 mg/5mL Jarabe",
                "Amikacina",
                "Amiodarona",
                "Amitriptilína",
                "Amlodipina",
                "Amlodipina",
                "Amoxicilina",
                "Amoxicilina + Ácido Clavulánico",
                "Amoxicilina 250 mg + Ácido Clavulánico 62.5 mg /5mL",
                "Amoxicilina 250mg/5mL Polvo para Suspensión",
                "Antiespasmódico (N-Butil Bromuro-Hioscina) 20 mg/1 ml",
                "Antiespasmodico N-Butil Hioscina-Bromuro de Hioscina",
                "Antigripal",
                "Antigripal (con Dextrometorfan 10 mg)",
                "Atenolol",
                "Atenolol",
                "Atenolol + Clortalidona",
                "Atenolol + Clortalidona 100 mg / 25 mg",
                "Azitromicina",
                "Azitromicina 200 mg/5mL Polvo para Suspensión",
                "Bajante De Suero",
                "Bastón Ajustable de Aluminio Cuatro Apoyos",
                "Bastón Ajustable de Aluminio un Apoyo",
                "Betahistina",
                "Betametasona 0.1% Crema",
                "Bismuto Subsalicilato Suspension Oral",
                "Bisoprolol",
                "Bolsa Colectora de Orina 2 L",
                "Bolsa Colectora de Orina Pediátrica 100 mL",
                "Budesonida 100 mcg/Inhalaion",
                "Cabestrillo Sencillo (L)",
                "Cabestrillo Sencillo (S)",
                "Cabestrillo Sencillo Medium",
                "Calamina Locion 0.15%",
                "Calcio Carbonato 600 mg + Vit. D3 400UI",
                "Candesartan",
                "Candesartan",
                "Captoprilo",
                "Carbamacepina",
                "Carbonato de Litio",
                "Carvedilol",
                "Carvedilol",
                "Carvedilol",
                "Catéter E.V. # 18",
                "Catéter E.V. # 20",
                "Catéter E.V. # 22",
                "Catéter E.V. # 24",
                "Cefalexina",
                "Cefalexina 250 mg/5mL Suspensión",
                "Ceftriazona 1g",
                "Cetirizina",
                "Cetirizina Jbe.5mg/5ml",
                "Ciprofloxacina",
                "Citicolina",
                "Claritromicina",
                "Claritromicina 250 mg/5mL Suspension",
                "Clindamicina",
                "Clindamicina Óvulo",
                "Clopidogrel",
                "Clorpromazina",
                "Clorpromazina",
                "Clorpromazina",
                "Clorpromazina",
                "Cloruro de Sodio 6.5 mg/ mL Gotas Nasales",
                "Clotrimazol 1% Crema",
                "Clotrimazol 1% Solucion",
                "Clotrimazol Ovulos",
                "Codera Larga",
                "Codera Mediana",
                "Collarín Blando Largo",
                "Collarín Blando Mediano",
                "Collarín Rígido Ajustable Grande",
                "Complejo B (Vit.B1 100 mg, B2 10 mg, B6 10mg, Nicotinamida",
                "Complejo B (Vit.B1 15mg + B2 1mg + B6 2.6mg + B12 2mcg + Nicotinamida 10mg)",
                "Complejo B (Vit.B1 50 mg + B6 50 mg + B12 200mcg ) 15 mL Jbe",
                "Decanoato de Flufenazina",
                "Deflazacort 6 mg Tableta Blíster",
                "Dexametasona",
                "DEXAMETASONA",
                "Dexametasona Fosfato Sódico Iny. IM-IV",
                "Dextrosa al 50% i.v.",
                "Diclofenac Sódico",
                "Diclofenaco Dietilamonio1.16% Gel",
                "Diclofenaco Sodico",
                "Dicloxacilina",
                "Difenhidramina",
                "Difenhidramina 10 mg/ml",
                "Difenhidramina 12.5 mg/5mL",
                "Digoxina",
                "Dimenhidrinato",
                "Dimenhidrinato 15 mg/5 ml Jarabe",
                "Doxiciclina",
                "Enalapril Maleato",
                "Enalapril Maleato",
                "Eritromicina 250 mg/5 mL",
                "Eritromicina Estearato",
                "Eritropoyetina Humana Jeringa Precargada",
                "Eritropoyetina Humana Liofilizada",
                "Espirómetro",
                "Espironolactona",
                "Espironolactona",
                "Estrogenos Conjugados",
                "Etinilestradiol + Levonorgestrel",
                "Fenitoína Sódica",
                "Fenitoina Sodica 125 mg/5mL Susp. Oral",
                "Fluconazol",
                "Fluconazol 50 mg/5mL Susp. Oral",
                "Fluoxetina",
                "Fosfomicina",
                "Fosfomicina 250 mg/5ml Susp. Oral",
                "Furosemida",
                "Gasa Precortada 4 X 4 Sobre",
                "Gentamicina 3mg/ml Gotas Oftalmicas",
                "Gentamicina Sulfato 40 mg/mL",
                "Glibenclamida 5 mg",
                "Gotas Oticas (Polimixina+Neomicina)",
                "Griseofulvina",
                "Guante Examen Medium # 71/2",
                "Guantes de Goma Nitrilo talla M C/100 unidad",
                "Guantes de Goma, Nitrilo talla L C/100 Unidad",
                "Haloperidol",
                "Haloperidol",
                "Haloperidol Gotas 2 mg/mL",
                "Heparina",
                "Hidralacina Clorhidrato",
                "Hidroclorotiazida",
                "Hidroclorotiazida",
                "Hidrocortisona 1% Pomada",
                "Hidrocortisona 100 mg",
                "Hidroxido de Aluminio +hidroxido de Magnesio Gel +Simeticona Suspension",
                "Hierro Sacarosa",
                "Ibuprofeno",
                "Ibuprofeno",
                "Imipramina Clorhidrato",
                "Inmovilizador De Muñeca Derecha",
                "Inmovilizador De Muñeca Izquierda",
                "Inmunoglobulina Antitetánica (Humana)",
                "Insulina Glargina Recombinante 100 UI/mL Jeringa Precargada",
                "Insulina Intermedia NPH 100 UI/mL Vial 10 mL",
                "Insulina Mixta 70/30 100 UI/mL Vial 10 mL",
                "Insulina Regular (Cristalina) 100 UI/mL Vial 10mL",
                "Ipratropio Bromuro 0.900 mcg/ml Sol. Para Nebulizar",
                "Itraconazol",
                "Jabón Antiséptico (Benzalconio) Pasta 100 g",
                "Jabón de Avena Pasta de 100 g",
                "Jabón de Azufre 10% Pasta de 100 gr.",
                "Jeringa 3 ml",
                "Jeringa 5 mL",
                "Jeringa 10 mL",
                "Jeringa Insulina",
                "Ketoconazol 2% Champú",
                "Ketoconazol 2% Crema",
                "Lactulosa 66.7 g/100 mL",
                "Levodopa + Benserazida",
                "Levofloxacina",
                "Levotiroxina",
                "Levotiroxina",
                "Levotiroxina",
                "Lisinopril",
                "Lisinopril",
                "Loratadina",
                "Loratadina 5 mg/5mL Jarabe",
                "Losartan",
                "Losartán Potásico",
                "Mariposita No.21",
                "Mariposita No.23",
                "Mariposita No.25",
                "Mascarilla para Nebulizar Adulto",
                "Mascarilla para Nebulizar Pediátrica",
                "Mebendazol",
                "Mebendazol",
                "Mecobalamina",
                "Metformina",
                "Metformina",
                "Metformina",
                "Metildopa",
                "Metil-Dopa",
                "Metoclopramida",
                "Metoprolol",
                "Metoprolol",
                "Metronidazol",
                "Metronidazol + Diyodohidroxiquinoleina",
                "Metronidazol + Diyodohidroxiquinoleina 400mg + 200mg",
                "Muleta Aluminio Adulto (L)",
                "Muleta de Aluminio para adolescentes (S)",
                "Muletas De Aluminio Grandes Para Adultos XL",
                "Mult. Lactante Sin Estim(Vit.A1500UI,D 400UI,C 35mg,B1 0.5mg,B2 0.5mg,B6 Niacinamina 8mg)",
                "Multivitaminas Prenatales",
                "Nafazolina 0.1% Solución Oftálmica",
                "Naproxeno",
                "Nifedipina",
                "Nifedipina",
                "Nistatina 100,000 UI Óvulos Unid",
                "Nistatina 100,000 UI/ mL Suspensión",
                "Nitrofurantoina (Macrocristales)",
                "Nitrofurazona 0.2% Pomada",
                "Olanzapina",
                "Olanzapina",
                "Omeprazol",
                "Orinal Para Hombre",
                "Orinal Plástico Desechable para Mujer",
                "Oxido de Zinc",
                "Pañal Desechable (S) 4-10kg",
                "Pañal Desechable Grande para Adultos (Large)",
                "Pañal Desechable Mediano para Adulto",
                "Pañal Desechable Niños (M) 9-15kg",
                "Pañal Desechable para niños L",
                "Pañal Desechable Pequeño para Adulto",
                "Pañal Desechable Recien Nacido 2-5 kg",
                "Penicilina G Benzatínica 1.2",
                "Penicilina G. Benzatínica 2,400,000 UI",
                "Penicilina G. Benzatínica 600,000 UI",
                "Penicilina G.Procaínica 4,00,000 UI .",
                "Penicilina G.Procaínica 4,000,000 UI .",
                "Penicilina G.Procaínica 400,000 UI",
                "Perita De Aspiración Nasal",
                "Permetrina 1% Champú",
                "Permetrina 1% Loción",
                "Permetrina 5% Crema",
                "Prednisona",
                "Prednisona",
                "Prednisona",
                "Pregabalina",
                "Pregabalina",
                "Preservativo Masculino",
                "Propanolol",
                "Propranolol",
                "Proteína Hiperprotética Suplemento Nutricional Líquido",
                "Proteína Polimérica con Probiótico",
                "Proteína Polimérica con Probióticos Líquida",
                "Proteína Polimérica en Polvo",
                "Proteína Polimérica Líquida",
                "Proteina Polimerica Modulo Proteico",
                "Quetiapina",
                "Quetiapina",
                "Ramipril",
                "Risperidona",
                "Risperidona",
                "Rodillera Grande",
                "Rodillera Mediana",
                "Rodillera Pequeña",
                "Salbutamol",
                "Salbutamol Sulfato 100 mcg/Inhalacion",
                "Salbutamol.P/Nebulizar 5mg/ml",
                "Sales de Rehidratación Oral",
                "Sertralina",
                "Simvastatina",
                "Simvastatina",
                "Solucion Ringer con Lactato Frasco 1000 ml",
                "Solución Cloruro de Sodio 0.9%",
                "Solucion Cloruro Dextrosa 0.5% + Cloruro de Sodio 0.33",
                "Solución Cloruro Sódico 0.9% Iny. I.V. Fco. 1000 ml",
                "Sonda Foley 2 Vías No.14",
                "Sonda Foley 2 Vías No.16",
                "Sucralfato Granulado 1 g",
                "Sulfadiazina Argéntica 1% Crema",
                "Sulfato de Zinc",
                "Sulfato Ferroso",
                "Sulfato Ferroso",
                "Sulfato Ferroso + Ácido Fólico",
                "Sulfato Ferroso 125 mg/mL Gotas",
                "Termometro digital oral",
                "Tinidazol",
                "Tobillera Grande",
                "Tobillera Mediana",
                "Tobillera Mediana Rigida",
                "Tobillera Pequeña",
                "Tobramicina 0.3% Gotas Oftálmicas",
                "Trimetoprim-Sulfametoxazol",
                "Trimetroprím-Sulfametoxazol (40/200mg) 5 mL",
                "Valsartán",
                "Vagina Elástica 3\" x 5 Yardas",
                "Venda Elástica 4\" x 5 Yardas",
                "Venda Elástica 6\" x 5 Yardas",
                "Verapamil 80 mg",
                "Vitamina A 50,000 UI",
                "Vitamina A Y D(3000 UI + 300 UI)",
                "Vitamina E 400 UI",
                "Vitaminas Neurotrópicas +Dexametasona + Dexametasona",
                "Vitaminas y Minerales",
                "Warfarina Sódica",
                "Yodopovidona Solución al 10%"
            ];

            $descriptions = [
                "Frasco 180 ml RD$40.00",
                "Tableta 500 mg RD$0.30",
                "Supositorio 100 mg RD$5.00",
                "Frasco Gotero 15 ml RD$15.00",
                "Frasco 120 ml RD$15.00",
                "Tableta 500mg/65 mg RD$25.00",
                "Vial RD$50.00",
                "Ampolla 300 mg/3 ml RD$15.00",
                "Tableta 400 mg RD$1.50",
                "Frasco 60 ml RD$40.00",
                "Tubo de 5 g RD$10.00",
                "Tableta 325 mg RD$1.00",
                "Tableta 81 mg RD$0.50",
                "Tableta 500 mg RD$2.00",
                "Tableta 5 mg RD$0.20",
                "Tableta 50 mg RD$12.00",
                "Frasco 40 ml RD$90.00",
                "Vial RD$10.00",
                "Ampolla 300 mg/3 ml RD$15.00",
                "Tableta 400 mg RD$1.50",
                "Frasco 60 ml RD$40.00",
                "Tubo de 5 g RD$10.00",
                "Tableta 325 mg RD$1.00",
                "Supositorio 100 mg RD$5.00",
                "Frasco Gotero 15 ml RD$15.00",
                "Frasco 120 ml RD$15.00",
                "Frasco 60 ml RD$40.00",
                "Ampolla 300 mg/3 ml RD$15.00",
                "Vial RD$50.00",
                "Tableta 200 mg RD$4.00",
                "Tableta 25 mg RD$1.50",
                "Tableta 5 mg RD$0.20",
                "Tableta 10 mg RD$0.20",
                "Capsula 500 mg RD$2.00",
                "Capsula 500 mg/125 mg RD$5.00",
                "Frasco 60 ml RD$25.00",
                "Sobre 400 mg/10 ml RD$5.00",
                "Tableta 400 mg RD$1.00",
                "Frasco 120 ml RD$25.00",
                "Frasco 120 ml RD$13.00",
                "Tableta 500 mg RD$0.70",
                "Tableta 50 mg RD$12.00",
                "Frasco 40 ml RD$90.00",
                "Ampolla 10 ml RD$3.00",
                "Ampolla 5 ml RD$3.00",
                "Frasco 60 ml RD$15.00",
                "Frasco 60 ml RD$15.00",
                "Frasco 30 ml RD$20.00",
                "Tubo 30 g RD$12.00",
                "Ovulo 100 mg RD$10.00",
                "Frasco 30 ml RD$20.00",
                "Vial RD$135.00",
                "Vial RD$550.00",
                "Vial 10 ml RD$110.00",
                "Vial 10 ml RD$110.00",
                "Vial 10 ml RD$110.00",
                "Ampolla RD$50.00",
                "Frasco 60 ml RD$200.00",
                "Frasco 120 ml RD$50.00",
                "Frasco 100 ml RD$50.00",
                "Unidad RD$10.00",
                "Unidad RD$5.00",
                "Unidad RD$150.00",
                "Unidad RD$200.00",
                "Unidad RD$150.00",
                "Unidad RD$150.00",
                "Unidad RD$350.00",
                "Vial 10 ml RD$20.00",
                "Vial 10 ml RD$20.00",
                "Vial 1000 ml RD$20.00",
                "Vial 1000 ml RD$40.00",
                "Frasco 1000 ml RD$20.00",
                "Unidad RD$20.00",
                "Unidad RD$20.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 30 g RD$50.00",
                "Tubo 30 g RD$12.00",
                "Frasco 100 ml RD$30.00",
                "Unidad RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Capsula 100 mg RD$20.00",
                "Frasco 120 ml RD$5.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 30 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00",
                "Frasco 100 ml RD$20.00",
                "Frasco 120 ml RD$20.00",
                "Frasco 60 ml RD$30.00"
            ];
            DB::table('drugs')->insert([
                'description' => fake()->randomElement($descriptions),
                'name' => fake()->randomElement($names),
                'prescription_details_id' => fake()->numberBetween(1, 10),
                'active' => fake()->boolean(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
